id: P000324
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:34:03.113458
source_metadata:
  id: bdr:W19471
  title: ཉམས་མགུར
  author: ''
  volumes:
    be155170bd534f6e944bdd77a28424d9:
      image_group_id: I2827
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
